with open("knr10.data","r")as fp:
    fp.seek(7)
    print("now fp points after seek()to:{}",format(fp.tell()))
    filedata=fp.read(7)
    print("filedata=",filedata)
    print("now fp points to:{}",format(fp.tell()))
    print("---------------------------------------------")
    fp.seek(4)
    print("now fp points seek() to :",format(fp.tell()))
    filedata=fp.read(4)
    print("filedata=",filedata)
    print("now fp points to:",format(fp.tell()))
    print("__________________________________")
    fp.seek(9)
    print("now fp points to :".format(fp.tell()))
    filedata=fp.read(9)
    print("filedata=",filedata)
    print("now fp points to:",format(fp.tell()))